spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mpriyankdev/learn_ms.git
          searchPaths: config_properties

server:
  port: 12500
